spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    sqlScriptEncoding: UTF-8
    url: jdbc:h2:mem:testdb
    initialization-mode: always

#    url: jdbc:postgresql://localhost:5432/app_db
#    driverClassName: org.postgresql.Driver
#    username: app_user
#    password:
#    initialization-mode: always

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, loggers
      base-path: /spy

  endpoint:
    health:
      show-details: always

info:
  application:
    name: spring-actuator
    description: spring boot actuator application
    version: 0.0.1-SNAPSHOT