spring:
  batch:
    job:
      enabled: true
    initialize-schema: always
  datasource:
#    sqlScriptEncoding: UTF-8
#    url: jdbc:h2:mem:testdb
#    initialization-mode: always

    url: jdbc:postgresql://localhost:5432/app_db
    driverClassName: org.postgresql.Driver
    username: app_user
    password:

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: test
